# Generated by Django 5.2.7 on 2025-10-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='bookcopy',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rental',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='returned_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='copy_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='ongoing', max_length=20),
        ),
    ]
